### ISSUE TITLE
[Feature] Able to display multiple views in dashboard

### ISSUE THREAD

**Issue by LazyTarget** [amoerie/teamcity-theatre#112]
We have seperated our different projects into their respective views.
It would be wonderful if we could see all of them in the same dashboard.
Currently it is only supported to display one at a time.

Suggestion 1:
Able to query which views to display using commas in the url.
Example: /dashboard/hello,foo,bar

Suggestion 2:
Instead of displaying the view picker, display the actual views?
Enable this feature with a query string or a global setting.

I wanted to implement this by myself, but my skills in TypeScript are too limited

**Comment by amoerie** [comment]
Couldn't you simply use a chrome addon for this? Like this one: [Revolver](https://chrome.google.com/webstore/detail/revolver-tabs/dlknooajieciikpedpldejhhijacnbda?hl=en)

**Comment by Sharken03** [comment]
I would agree that this is not a core feature, as a good solution is already available (using an extension).

**Comment by amoerie** [comment]
I guess the answer to use Revolver is acceptable. Closing this issue, please create a new one if you feel this resolution is not satisfying to you.

**Comment by LazyTarget** [comment]
@amoerie 
Didn't see the answer by @Sharken03 
I see the appeal with Revolver, however I would still prefer to have them in the same tab. Especially when I have just a few on each view, leaving the rest of the screen space unused.

Is this enough to reconvince you guys to reopen? 😄
