### ISSUE TITLE
Limit display of old/inactive branches

### ISSUE THREAD

**Issue by gregmac** [amoerie/teamcity-theatre#12]
We use feature branches extensively, and so there's now a handful of old branches (mostly on lesser-used projects) that are being displayed, some with last builds a couple of months ago. The branch has since been integrated (or dropped), but stays up on teamcity-theatre anyway.

---
## Option 1: Only show 'active' branches

This would only show branches that also show as Active in Teamcity's UI. 

There is an "experimental" feature that allows this (https://youtrack.jetbrains.com/issue/TW-44148): request `../app/rest/buildTypes/<locator>/branches?locator=policy:ACTIVE_HISTORY_AND_ACTIVE_VCS_BRANCHES`. 

This may be difficult. The current list of builds is loaded for all branches at once: https://github.com/amoerie/teamcity-theatre/blob/master/src/TeamCityTheatre.Application/DataServices/BuildDataService.cs#L28

This would have to be filtered to include only the active branches returned from this new API call. 
## Option 2: Filter by time

Essentially, remove any branch that was last built more than x days ago. "x" would have to be configurable, though not sure if it would be for the dashboard or per-build. 

I think this can be done by just add a .Where clause here:  https://github.com/amoerie/teamcity-theatre/blob/master/src/TeamCityTheatre.Application/QueryServices/TileService.cs#L28).

**Comment by amoerie** [comment]
Hi Greg.

We have noticed the same problem, and usually the offending branch disappears after a short while because the activity in other branches pushes it out.

However, we also have some very inactive projects that keep on showing these outdated builds.

While your 2 options are considerable, I would much prefer to actually use the VCS root api somehow to detect if a branch still exists there. If a branch is removed from git, we can filter it out.

This would avoid the need for a filter by time or an experimental feature (if it goes out of experimental status, it seems like the better option though)

If you happen to have a working version, feel free to submit a pull request. Otherwise, you'll have to wait for whenever I find some time to continue work on this. :smiley:

**Comment by gregmac** [comment]
I poked around, but I don't see a way to get the list of existing branches via VCS root API, unfortunately.

I still do think the best way is to simply mirror what the TeamCity UI thinks are 'active' branches; it's just unfortunate that it's an 'experimental' API.

It could simply be written in a way so it filters the builds after, and if that API fails for some reason, it defaults to just not filtering, which would be identical to how it works now. Would you be okay with this? I may give it a shot if I have time.

On a related note: TeamCity 10.0 came out today, wonder if the experimental API is still in?

**Comment by amoerie** [comment]
The TeamCity 10 REST Api documentation contains the following example:

`GET http://teamcity:8111/httpAuth/app/rest/builds/aggregated/strob:(branch:(buildType:(id:BUILD_CONF_ID),policy:active_history_and_active_vcs_branches),locator:(buildType:(id:BUILD_CONF_ID)))/statusIcon.svg`

See https://confluence.jetbrains.com/display/TCD10/REST+API

There seems to be no mention of any experimental status... so it's safe to say that this is the way to go.
I would definitely be okay with this fix and would accept a proper pull request!

If you're willing to wait, I might find some time for this in the coming three weeks.

**Comment by gregmac** [comment]
I haven't upgraded to Teamcity 10 yet, but I can verify this doesn't work with 9.x. Looks like it might be really easy (just adding that policy filter to the existing request) but it looks like it might be a while before I can get upgraded. 

What's the policy on backwards compatibility? Eg, should this filter only be added if version >=10, to avoid breaking compatibility with 9.x, or does this just get a bump and requirement that you're on TC10?

**Comment by amoerie** [comment]
Hi @gregmac 

Sorry for the long delays, my free time is scarse it would appear. 

Anyways, I'm adding the policy:active_history_and_active_vcs_branches filter by default, as discussed.
Are you still using TeamCity 9.x?

I might indeed just update the docs to require TeamCity 10.x and older, but I can always add backwards compatibility settings if the need exists.

I'm currently in the process of rewriting the frontend in Rx + React, when that is finished I'll release a new version with this solution included.

**Comment by amoerie** [comment]
This option is now enabled by default, if it breaks for people still using TeamCity 9.x let me know so I can find a workaround for this.

**Comment by Sizigmund** [comment]
The request you`re looking for looks like 
.../app/rest/buildTypes/id:YOUR_BUILDTYPE_ID/branches?locator=policy:all_branches
Devs of TC api have providen enough descriptive error messages in case of wrong api requests.
For example, in case of wrong value for policy dimension: 
Details: jetbrains.buildServer.server.rest.errors.BadRequestException: Invalid value 'all_branche' for 'policy' dimension. Supported values are: [VCS_BRANCHES, ACTIVE_VCS_BRANCHES, HISTORY_BRANCHES, ACTIVE_HISTORY_BRANCHES, ACTIVE_HISTORY_AND_ACTIVE_VCS_BRANCHES, ALL_BRANCHES]
