### ISSUE TITLE
Having customizable tile size

### ISSUE THREAD

**Issue by faacunha** [amoerie/teamcity-theatre#13]
I'm using teamcity theatre on a 48 inch tv, yet, the tiles stay as small as using on a 15 inch monitor.

Sometimes even the full branch name doesn't fit.

This is probably possible to change if I go around overwriting CSS's but I think we should have a more elegant customizable way of setting tile size

**Comment by amoerie** [comment]
I agree. Sorry for the late reply!

I'll look into using an alternative to the bootstrap grid system to see if I can find a more elegant solution.
Maybe configurable rows and columns, like you say, would be best.

**Comment by amoerie** [comment]
3.0 will add the ability to specify the number of columns per view! 🎉
