### ISSUE TITLE
Dashboard Stopped working

### ISSUE THREAD

**Issue by JasKik** [amoerie/teamcity-theatre#140]
Hi All

Dashboard stopped working yesterday - just has loading view data spinning but never renders.

**Comment by amoerie** [comment]
There wasn't a new release yesterday.. ? 

Can you check the TeamCity log files? In appsettings.json you'll find the directory it's writing to, and the files should be called `TeamCityTheatre.Web-{yyyyMMdd}.log`, for example `TeamCityTheatre.Web-20190603.log`

**Comment by JasKik** [comment]
OK Thanks  - there was an error logged - Data At Root Level is invalid. I removed all tiles and added back solved the  problem. Not really sure what caused the issue though.

**Comment by amoerie** [comment]
Did you perhaps delete a build configuration? TeamCity doesn't like it when that happens.
The error "Data at root level is invalid" probably means the REST API returned an error instead of the expected data.

**Comment by amoerie** [comment]
Anyway thanks for reporting back, and glad to hear your problem is solved!
