### ISSUE TITLE
Idea: Show queue position for pending builds

### ISSUE THREAD

**Issue by Sharken03** [amoerie/teamcity-theatre#28]
If you have a lot of build configurations and not so many Agents, then a lot of those builds might be put on the Build Queue due to not having enough Agents for all builds. 
It would be great if you could see what position a build has in the Build Queue along with the total number of builds waiting in the queue.

If there is enough space, you could also display when TeamCity estimates that the build will start and finish, alternatively just when the build is supposed to start.

**Comment by amoerie** [comment]
I'm afraid this is outside the scope of this project. This is a project to monitor builds as they happen or have happened, not what's coming in the queue. This information would also have to be fetched separately, and I think we're already spamming the TeamCity REST API enough as it stands today 😆

**Comment by Sharken03** [comment]
Fair enough although a [dedicated build node](https://confluence.jetbrains.com/display/TCD18/Several+Nodes+Setup) would probably mean that the server would be able the added load.
So its something to look at if you ever run out of ideas :)
