### ISSUE TITLE
Unable to create View

### ISSUE THREAD

**Issue by alwaysharsha** [amoerie/teamcity-theatre#3]
Now i have new issue, Where i am unable to create new view. 

Below is the error message.
-----------------------------------------------------------------------------------------------------
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
angular-loader.js:7 POST http://localhost:8080/api/views 500 (Internal Server Error)(anonymous function) @ angular-loader.js:7n @ angular-loader.js:7f @ angular-loader.js:7(anonymous function) @ angular-loader.js:7n.$eval @ angular-loader.js:7n.$digest @ angular-loader.js:7n.$apply @ angular-loader.js:7(anonymous function) @ angular-loader.js:7n.event.dispatch @ angular-loader.js:225r.handle @ angular-loader.js:225
angular-loader.js:7 POST http://localhost:8080/api/views 500 (Internal Server Error)

**Comment by alwaysharsha** [comment]
This issue comes if the file configuration.json already exists.

**Comment by amoerie** [comment]
Could you perhaps post the error? In chrome, in the network tab, you should be able to open the request that failed and inspect the response body. There you should the default error page, which would help me find the problem. Thanks!

**Comment by amoerie** [comment]
Closing because no further information?
