### ISSUE TITLE
teamcity-theatre-3.0 deployment issue

### ISSUE THREAD

**Issue by lprashanth** [amoerie/teamcity-theatre#30]
The previous version on .NET 1.x.x works fine.  Could you please specify exact .NET version steps, attached error.
![capture](https://user-images.githubusercontent.com/11000305/40209566-99fb1cdc-5a05-11e8-937a-2d9ebe4ec517.PNG)

http://localhost/dashboard

Thank you.

**Comment by amoerie** [comment]
Ah yes, this update requires .NET Core 2. I''ll update the docs!

**Comment by amoerie** [comment]
Docs are updated.
