### ISSUE TITLE
run in docker

### ISSUE THREAD

**Issue by tobiaszuercher** [amoerie/teamcity-theatre#31]
hey, 
cool project! any plans to buld a docker image?

cheers
tobi

**Comment by amoerie** [comment]
I'm always open to PRs, but I'm not going to make one, since I don't use it and don't know how it works. 😉 

But is it necessary though? Couldn't you use some existing image and then deploy teamcity theatre on there? I can't imagine there would be a lot of steps involved..

**Comment by tobiaszuercher** [comment]
don't want to go into docker vs iis. but there are many reasons not to host in iis :) with netcore, it's also super easy.

maybe i'm doing a PR  as soons as i have more time

**Comment by amoerie** [comment]
I'm working on this now, see the 'docker' branch. It's a work in progress though.

**Comment by trolleyyy** [comment]
I'm very glad to hear that you enjoy this solution. Talking about things, you have doubts about: the reasons my solution looks like this are following:
- It was the cheapest solution I've managed to create which still offers some configuration capabilities and it is stable - building image works both from windows and linux host. We just needed tool :)
- I had particurally no knowledge yet about react and yarn stuff :) I just wanted to run your decomposed 'publish.sh' script to work in Docker.
- I wanted to make as little as possible changes.
- It is still multistage build, result image is not heavy.

I agree with your ideas - both the solution using yarn from node image containing this tool already and getting host, username and password from environment variables inside app sounds great.

Unfortunately I'm not sure when I'll be able to develop them - for now we want to develop some other stuff on this project (i.e. display number of tests passed/skipped/failed on tile which was shown in visuwall we moved to tc-theatre from).

**Comment by amoerie** [comment]
Hey no need to defend yourself, it was more me thinking out loud! Like I said, I really appreciate the work you did and I can learn a few things from your changes! 
The way it is looking now, I'm probably going to incorporate some of your changes into my docker branch and try to get that working, so we can have some "best of both worlds" going on.

May I assume you have some .sh / .cmd script that launch the Docker image with the proper environment variables? Because I'm also thinking in that direction now.

**Comment by amoerie** [comment]
Oh and feel free to open other issues related to the visuwall features you speak about. I'm not exactly a role model maintainer (have a lot of things going on in my life) but I am always willing to consider things and help around where I can!

**Comment by trolleyyy** [comment]
Sorry, we don't have such script for now - I just ran it manually. But we'll probably finally create one - a service script registered within systemctl.

Anyway - writing from my memory - it goes sth like this:
`sudo mkdir /var/docker/volumes/tc-theatre`
`sudo chmod 775 /var/docker/volumes/tc-theatre`
`sudo echo "{}" > /var/docker/volumes/tc-theatre/configuration.json`
`sudo chmod 664 /var/docker/volumes/tc-theatre/configuration.json`
`docker run -d --name tc-theatre -p 10180:80 -v /var/docker/volumes/tc-theatre:/app/data -e TEAMCITY_HOST=http://teamcity -e TEAMCITY_USER=foo -e TEAMCITY_PWD=bar teamcity-theatre`

**Comment by trolleyyy** [comment]
Ah, and for build is of course: `docker build --tag teamcity-theatre -f linux.Dockerfile .` run from directory when linux.Dockerfile resides.

**Comment by amoerie** [comment]
I'm making good progress on this (see my 'Docker' branch) but some things are still behaving strange: Restsharp seems to be iffy with URL segments all of a sudden, and for some reason the dates of builds aren't coming through properly.

But I have managed to make a complete and correct build in Docker without any platform specific code so far, so I'm hoping you could help me verify everything will work on Linux @trolleyyy, if you have a moment?

Anyway, I really like the way this works so far, I also want to move the Travis builds to Docker to align everything. Great stuff!

**Comment by amoerie** [comment]
@trolleyyy I seem to have a decent working version of TeamCityTheatre using Windows Containers, would you be willing to review the 'docker' branch? I still have to write documentation, but you can add environment variables now:

TEAMCITYTHEATRE_CONNECTION__URL
TEAMCITYTHEATRE_CONNECTION__PASSWORD
TEAMCITYTHEATRE_CONNECTION__USERNAME

*Note that double underscore in the second part!! (https://github.com/aspnet/Configuration/issues/469)*

and it'll get picked up during application startup. I've also added logging that prints these variables on startup, so you can be 100% sure whether it's picking them up. 

I don't think there's any Windows specific code in the application or the Dockerfile, so to run this on Linux all you'd need to do is replicate and modify the "docker build.cmd" and "docker run.cmd" files in bash, which don't contain a lot of logic. (Mostly calling docker build and docker run)

**Comment by amoerie** [comment]
Closing this issue, please create new specific issues when problems occur related to Docker support, thanks!
