### ISSUE TITLE
Improving the cosmetics.....

### ISSUE THREAD

**Issue by natiki** [amoerie/teamcity-theatre#35]
Hi,

I am guessing you have some custom CSS doing the look and feel you indicate in https://camo.githubusercontent.com/e9c4162aa89d763516f0aaeb3c09fd4392f6811c/687474703a2f2f692e696d6775722e636f6d2f697a5a695756642e706e67

Mainly because you are using branches. In our case we don't have the branch information available from TeamCity. So after adding my projects to a single view I have:

![image](https://user-images.githubusercontent.com/4738140/44566951-94aab480-a7b3-11e8-8584-759da83bbdd4.png)

- No block separation
- No last / build time

Any chance theatre could pull this hightlighted information information?

![image](https://user-images.githubusercontent.com/4738140/44567142-67123b00-a7b4-11e8-9ccb-d1b38ae6ada2.png)

**Comment by amoerie** [comment]
Actually the application will detect if branch information is not available (is null) and will fall back to showing the version number in usual circumstances. I am surprised to not see them? 

Could you check the logs and see which data is returned from TeamCity?

**Comment by ylerner43** [comment]
I have the same issue. What can we do about it. TC 2018.1.2
![image](https://user-images.githubusercontent.com/17621491/45702833-7462e100-bb38-11e8-91fb-ec7455863b3a.png)

**Comment by natiki** [comment]
@amoerie I have not forgotten about this. Still need to come back to this. At the moment the fact that even when builds fail the board still shows green which is my bigger issue. Once I get back to this I will investigate the logs here as well.

**Comment by amoerie** [comment]
Until one of you can provide logs, I would suggest debugging the problem yourselves. Theres an npm script to build a non production version of the JS files which should be fairly readable, although you will need a bit of RxJs basics to follow the business logic. Setting breakpoints in the React components might suffice to find the problem though.

**Comment by amoerie** [comment]
Apologies about my lack of activity by the way, I've been quite busy. I hope to catch up with some outstanding issues here as soon as I can.

**Comment by amoerie** [comment]
In the absence of any further feedback or logs to diagnose this problem, I am closing this issue. 

If anyone reading this is still encountering this issue, please create a new issue containing any log files, screenshots or other info you might have so I might be able to diagnose the problem. It's hard to help without knowing what's going wrong. I hope you understand, thanks.
