### ISSUE TITLE
Some amount of user management

### ISSUE THREAD

**Issue by alwaysharsha** [amoerie/teamcity-theatre#4]
I would like to see users can login using LDAP and select the view they are interested or create new one, instead of viewing all the views by default.

Also, ability to search for existing views based on keywords or view name.

**Comment by amoerie** [comment]
Wait, users? You do know this application is supposed to be used on a wall mounted screen right? 
Although of course you can do with it whatever you want, but there is no concept of "users" in this project and that was a deliberate decision.

I'll write down your suggestion to search for views in a separate issue! Although I do raise my eyebrows wondering why you would have so many views you need to search through them...
