### ISSUE TITLE
Avoid duplicate entries of same job in the view

### ISSUE THREAD

**Issue by alwaysharsha** [amoerie/teamcity-theatre#5]
Can you avoid adding duplicate entries of same job in the view, just display a warning while adding.

**Comment by amoerie** [comment]
While I appreciate the idea, I think it's not worth the hassle.
It's easy and fast to delete a job, and the whole setup part is usually something you don't do every day anyway. 

If you submit a pull request though I'll happily accept. :-)

**Comment by amoerie** [comment]
Not fixed in dotnetcore branch, but I still don't think this is very necessary.
