### ISSUE TITLE
Add summary of job status in the Dashboard view

### ISSUE THREAD

**Issue by alwaysharsha** [amoerie/teamcity-theatre#6]
The page which shows the various views available, can you just add the summary of how many are in Red, Building and Green.  That would be a great feature when someone has multiple views.

Which can act as an quick insight of the job status.

**Comment by amoerie** [comment]
Interesting idea! This should be fairly doable as most of the infrastructure is already there.

**Comment by amoerie** [comment]
Decided against this for the following reasons:

- When is it red? If the default branch fails? Slightly tricky to display accurate information
- This would require fetching all data for all views, which bombards the TC server if you have a lot of views. Making a performant backend for this would require special requests.

All in all, it doesn't seem worth the trouble.
