### ISSUE TITLE
Project name is long can it be displayed in multiple lines

### ISSUE THREAD

**Issue by alwaysharsha** [amoerie/teamcity-theatre#8]
Usually our project names are Main-Build-Dev-Layout, in this case i just see Main-Build-D... it would be difficult to identify which project it is.

**Comment by amoerie** [comment]
You can overwrite them with custom labels, so you could rename them to "MBDL".

If I allow two lines for the project name, that seriously screws up the tile layout.
Another option would be the use some form of "marquee" css where the name scrolls horizontally all the time, although I'm not sure if that would be too "busy".
